In [1]:
import scrapy

In [2]:
l = [23245, 27, 546, 215, -1234]

In [3]:
l

[23245, 27, 546, 215, -1234]

In [4]:
import numpy as np

In [7]:
a = np.array(l)

In [8]:
a

array([23245,    27,   546,   215, -1234])

In [9]:
b = np.array([12, 455, 63.3, True, "abc"])

In [10]:
b

array(['12', '455', '63.3', 'True', 'abc'], dtype='<U32')

In [11]:
#------------------

In [12]:
a

array([23245,    27,   546,   215, -1234])

In [13]:
a[2:]

array([  546,   215, -1234])

In [14]:
a[2:4]

array([546, 215])